import setuptools
from altonomy.ace import __version__

setuptools.setup(
    name='altonomy-ace-services',
    packages=setuptools.find_namespace_packages(include=["altonomy.*"]),
    include_package_data=True,
    description='Altonomy Ace Services',
    long_description=open('README.md').read(),
    version=__version__,
    url='',
    author='Bie Yaqing',
    author_email='yaqing.bie@altonomy.com',
    python_requires='>=3.6.0',
    keywords=['pip', 'altonomy', 'ace', 'services'],
    entry_points = {
        'console_scripts': [
            'alt_ace_pull_xalpha_deals = altonomy.ace.console_scripts.pull_xalpha_deals:main',
            'alt_ace_pull_tickers = altonomy.ace.console_scripts.pull_nitro_tickers:main',
            'alt_ace_subscriber = altonomy.ace.zmq_sub_client:main',
            'alt_ace_2 = altonomy.ace.v2.ace_client:main',
            'alt_athena_2 = altonomy.ace.v2.athena_client:main',
            'elwood_process_transfer = altonomy.ace.elwood_process_transfer:main',
            'send_live_balance = altonomy.ace.console_scripts.live_balance_snapshot:main',
        ]
    },
    install_requires=[
        "SQLAlchemy~=1.4.46",
        "alembic",
        "pymysql",
        "passlib",
        "fastapi==0.99.1",
        "fastapi-scheduler==0.0.12",
        "fastapi_amis_admin==0.5.7",
        "uvicorn<=0.18.2",
        "async-exit-stack",
        "async-generator",
        "requests",
        "PyJWT",
        "cryptography",
        "slackclient",
        "flake8",
        "pytest",
        "pytz",
        "pyzmq",
        "redis",
        "schedule",
        "python-multipart",
        "python-dateutil",
        "structlog",
        "boto3",
        "altonomy-settlement-engine",
        "altonomy-client>=0.4.37",
        "aiosqlite",
        "slack-sdk",
        "pandas",
        "dataframe_image",
        "lxml",
        "tabulate",
        "sqlmodel==0.0.11"
    ])
